# Generated by Django 5.2.2 on 2025-06-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=20)),
                ('last_emailId', models.EmailField(blank=True, max_length=20, unique=True)),
                ('mobile_no', models.IntegerField(max_length=10)),
                ('address', models.TextField()),
            ],
        ),
    ]
